name: Build and deploy .NET Core application to Web App JuniorTriWizardTournament20230613153930
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: JuniorTriWizardTournament20230613153930
  AZURE_WEBAPP_PACKAGE_PATH: JuniorTriWizardTournament\publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  WORKING_DIRECTORY: JuniorTriWizardTournament
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore dependencies
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}
      - name: Build
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: Publish
        run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.JuniorTriWizardTournament20230613153930_5059 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        env: # Define environment variables here
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
  deploy:
    runs-on: windows-latest
    needs: build_and_deploy_job
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.JuniorTriWizardTournament20230613153930_5059 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
