name: Build and deploy .NET Core application to Web App JuniorTriWizardTournament20230613153930
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: JuniorTriWizardTournament20230613153930
  AZURE_WEBAPP_PACKAGE_PATH: JuniorTriWizardTournament\publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  WORKING_DIRECTORY: JuniorTriWizardTournament
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_GROUND_0B14B7E10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "juniortriwizardtournament/client" # Your app source code path!!!
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
        env: # Define environment variables here        
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
  deploy:
    runs-on: windows-latest
    needs: build_and_deploy_job
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.JuniorTriWizardTournament20230613153930_5059 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
